[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FitFusion"
authors = [{name = "Group 5B", email = "up2225592@myport.ac.uk"}]
dynamic = ["version", "description"]
